### ISSUE TITLE
several questions about SpaText

### ISSUE THREAD

**Issue by fido20160817** [omriav/spatext#2]
Hi, Omri, I have read your SpaText paper. Following are my questions:

1. During training, why the number of segments is set to a value between 1 and 3?

2. I didn't see any clue about the global text prompt (description for the background of a training image) in L_simple in your paper, so how to train this condition in a classifier-free guidance manner (I mean how do you integrate the global text prompt into the model during training, and according to L_simple, I think your fine-tune model is language-free )

3. A prior alignment model was separately trained ahead, so for small areas in the training image, why not obtain these area's representation through firstly CLIP text embedding then image embedding through the prior model, and get a final ST representation containing small segments in the training image?

**Comment by omriav** [comment]
Hi,

Thank you for your interest in our work.
1. We specifically addressed the case of "sparse segmentation maps" in this work, where the user provides only a small number of segments (1-3), which is easier for most novice users. There is no real limitation to training the model on more segments.
2. We do not train the model on the global text prompt but on the CLIP image embeddings. During inference, we embed the global text prompt using the CLIP text encoder and then translate it into CLIP image embedding space using the prior model.
3. This is a very interesting idea! The only problem is that we do not have dense captions for each segment during training, so we cannot obtain the area's representation that way.

Best,
Omri

**Comment by fido20160817** [comment]
Thanks for your response. 
Best, 
Hao
